[package]

name = "mod_parallax"
version = "0.0.5"

[lib]
name = "mod_parallax"
crate-type = ["dylib"]

[dependencies]
interpolate_idents = "*"

[dependencies.apache2]
git = "https://github.com/majorz/apache2-rs.git"
